# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class J2y < Formula
  desc "A fast JSON to YAML converter."
  homepage "https://github.com/LJTian/j2y"
  version "1.0.1-rc1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/LJTian/j2y/releases/download/v1.0.1-rc1/j2y_1.0.1-rc1_darwin_amd64.tar.gz"
      sha256 "8ef4084be0103a0bca2b24ff46492708a29de1e1d7fbe8ba73ba1ffa26418142"

      def install
        bin.install "j2y"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/LJTian/j2y/releases/download/v1.0.1-rc1/j2y_1.0.1-rc1_darwin_arm64.tar.gz"
      sha256 "88d8c5c97bee953d2ae3f6496088e849ca4a3da63f910c4ee1aa5bfa6a7a9be2"

      def install
        bin.install "j2y"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/LJTian/j2y/releases/download/v1.0.1-rc1/j2y_1.0.1-rc1_linux_amd64.tar.gz"
      sha256 "4b7a5a3348ea1f5550b00a1aceb286982571162ed76f2337cf0d729df78d2da9"
      def install
        bin.install "j2y"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LJTian/j2y/releases/download/v1.0.1-rc1/j2y_1.0.1-rc1_linux_arm64.tar.gz"
      sha256 "cc0ec22601d55899ff78ac8561109f4c4ac61b00600431a113cb2b647e942b59"
      def install
        bin.install "j2y"
      end
    end
  end
end
